### ISSUE TITLE
Add missing challenge hints/solutions

### ISSUE THREAD

**Issue by bkimminich** [bkimminich/pwning-juice-shop#24]
## Hints
- [x] Successfully redeem an expired campaign coupon code
- [x] Post a product review as another user or edit any user's existing review
- [x] Steal someone else's personal data without using Injection
- [x] All your orders are belong to us! Even the ones which don't
- [x] Solve the 2FA challenge for user "wurstbrot"
- [x] Identify an unsafe product that was removed from the shop and inform the shop which ingredients are dangerous
- [x] Dumpster dive the Internet for a leaked password and log in to the original user account it belongs to
- [x] Infect the server with juicy malware by abusing arbitrary command execution
- [x] Request a hidden resource on server through server

## Solutions
- [x] Successfully redeem an expired campaign coupon code
- [x] Post a product review as another user or edit any user's existing review
- [x] Steal someone else's personal data without using Injection
- [x] All your orders are belong to us! Even the ones which don't
- [x] Solve the 2FA challenge for user "wurstbrot"
- [x] Identify an unsafe product that was removed from the shop and inform the shop which ingredients are dangerous
- [x] Dumpster dive the Internet for a leaked password and log in to the original user account it belongs to
- [x] Perform a persisted XSS attack through an HTTP header
- [x] Like any review at least three times as the same user
- [x] Infect the server with juicy malware by abusing arbitrary command execution
- [x] Request a hidden resource on server through server

**Comment by bkimminich** [comment]
@CaptainFreak @wurstbrot @J12934 For the missing GSoC 2018 challenge hints/solutions marked with ":man_shrugging:" I'd be very glad to get some input from your side. Some bullet points in this ticket would do, no need for you to write it up and post a PR. I just need some place to start or a list of typical steps an attacker would take. Thank you!

**Comment by bkimminich** [comment]
For 🤷‍♂️s: http://blog.shoebpatel.com/2018/08/05/OWASP-Juice-Shop-Challenge-Pack-2018-GSoC-project-report/

**Comment by J12934** [comment]
Oh shit, sorry forgot to answer you. 
I'll try to go over these in the next few days and write down what i can remember about them.

**Comment by bkimminich** [comment]
No problem, with Shoebs blog post things should be easier to write up finally! 😅

**Comment by omerlh** [comment]
Add a solution for the CSRF challenge on the profile page.

**Comment by bkimminich** [comment]
> Add a solution for the CSRF challenge on the profile page.
Do you mean the XSS on the profile page? That is already in the book.

**Comment by omerlh** [comment]
No - the CSRF issue (you can update the username/image/image URL with CSRF)

**Comment by bkimminich** [comment]
Ah, okay, but that's not a challenge... yet... 🤔

**Comment by omerlh** [comment]
Ohh yes, that's right. Want me to file an issue to add a challenge

**Comment by bkimminich** [comment]
That'd be great, thank you! 👍

**Comment by omerlh** [comment]
Done (see bkimminich/juice-shop#902)

**Comment by bkimminich** [comment]
Slowly but steadily closing in on 100% challenge coverage in the ebook ... for the two 🤷‍♂-challenges some help would still be appreciated, as I have a hard time to reproduce a sensible series of steps to get from A to B ...
