### ISSUE TITLE
https://github.com/bkimminich/pwning-juice-shop/blob/master/appendix/README.md#access-a-salesmans-forgotten-backup-file

### ISSUE THREAD

**Issue by tghosth** [bkimminich/pwning-juice-shop#3]
Has the answer in this file gone missing? It didn't seem to be there but I did not want to investigate too much to avoid spoilers...

**Comment by bkimminich** [comment]
The answer is in there, and the link from the overview table also works for me. Please provide a screenshot or a few more details how you try to access the solution and what book format you use.

I just tested with online reader.

**Comment by tghosth** [comment]
I am just using github to view the files. 

When I use the link: https://github.com/bkimminich/pwning-juice-shop/blob/master/appendix/README.md#access-a-salesmans-forgotten-backup-file it doesn't jump to anywhere within the file, it just stays at the top. When I search for "sales" on https://github.com/bkimminich/pwning-juice-shop/blob/master/appendix/README.md, it only returns me two results, neither of which are the answer.

However, if I go to the raw view, I can see that the heading exists in there so not sure why it is not showing in the browser.

The only hint I can find is that after the word "Visit" inside the answer for "Provoke an error that is not very gracefully handled.", the formatting changes a little and some text seems to be missing...

**Comment by bkimminich** [comment]
Ah, okay, now I get it. The anchor syntax used in the Markdown is for GitBook, which is partially incompatible with GitHub-flavored Markdown. But it shouldn't be _so broken_ that it doesn't show entire sections on GitHub... 😞

I cannot optimize for GitBook and GitHub viewing in parallel, so browsing the content on https://www.gitbook.com/book/bkimminich/pwning-owasp-juice-shop is the best possible fix, sorry.

**Comment by bkimminich** [comment]
![image](https://cloud.githubusercontent.com/assets/3531020/22177982/057afb0e-e02b-11e6-9230-bf3e8b0c0d14.png)

I clarified the description a bit as a kind of workaround/warning.
