### ISSUE TITLE
Create release for v8.4.0

### ISSUE THREAD

**Issue by wesrice** [bkimminich/pwning-juice-shop#34]
Hello @bkimminich. Thanks for all your work on this awesome project!

I'm wondering, can you please create a release for the 8.4.0 version of "Pwning Juice Shop?" One exists for 8.3.0, and I just noticed that you just released version 8.5.0 of Juice Shop. I have a CTF event all set up for next week using v8.4.0, and I want to ensure that I can distribute a 8.4.0 compatible copy of "Pwning Juice Shop."

Thanks!

**Comment by bkimminich** [comment]
I can tag the last version that was for 8.4.0, no problem.

**Comment by bkimminich** [comment]
Here you go: https://github.com/bkimminich/pwning-juice-shop/releases/tag/v8.4.0
