### ISSUE TITLE
Page Not Found on Readme of Hacking Preparations (Part 1)

### ISSUE THREAD

**Issue by GYeyosi** [bkimminich/pwning-juice-shop#37]
The Readme file of Hacking Preparation says **Please just make sure that you flipped through the existing [troubleshooting guide](https://github.com/bkimminich/juice-shop/blob/master/TROUBLESHOOTING.md) first.**  

Is the file is intentionally removed?
Should it be removed from the documentation?

**Comment by bkimminich** [comment]
No, the troubleshooting info was just moved into the ebook itself. That link is simply not updated. Thanks for spotting it! 👍
