### ISSUE TITLE
****** SPOILERS ***** KeePass

### ISSUE THREAD

**Issue by rogueresistor** [bkimminich/pwning-juice-shop#47]
Hey,

Has anyone solved the KeePass challenge using MacPass or some other tool on MacOS to open the KeePass database? So far I have not been successful using KeePassX, MacPass, or kpcli.

Thanks!

**Comment by bkimminich** [comment]
The KeePass DB file was created with the original Windows client. I have no MacOS device, so I don't know if it works with any client for it.
